import Link from "next/link";

export default function T3pPage() {
  const sections = [
    {
      href: "/t3p/input-generator",
      title: "Input File Generator",
      desc: "Interactive form to build a valid .t3p input file. Configure boundary conditions, bunch parameters, time stepping, monitors, and linear solver.",
    },
  ];

  return (
    <div className="p-8 max-w-4xl">
      <header className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900">T3P</h1>
        <p className="text-gray-500 mt-2">
          Time-domain wakefield simulation solver for particle accelerator
          structures. T3P computes wakefields generated by relativistic charged
          particle bunches traversing RF cavities and other accelerator
          components using higher-order finite elements on unstructured
          tetrahedral meshes.
        </p>
      </header>

      <section className="mb-8">
        <h2 className="text-lg font-semibold mb-2">Capabilities</h2>
        <ul className="text-sm text-gray-700 space-y-1 list-disc pl-5">
          <li>
            Longitudinal and transverse wakefield calculation for arbitrary
            cavity geometries
          </li>
          <li>
            Gaussian bunch excitation with configurable sigma and charge
          </li>
          <li>
            Moving window technique for efficient long-range wake computation
          </li>
          <li>
            Impedance calculation from time-domain wake potential via Fourier
            transform
          </li>
          <li>
            Volume field monitors for time-resolved electromagnetic field
            snapshots
          </li>
          <li>
            Absorbing boundary conditions to suppress spurious reflections
          </li>
        </ul>
      </section>

      <section>
        <h2 className="text-lg font-semibold mb-4">Tools</h2>
        <div className="space-y-3">
          {sections.map((s) => (
            <Link
              key={s.href}
              href={s.href}
              className="block p-4 bg-white border border-gray-200 rounded-lg hover:border-blue-300 hover:shadow-sm transition-all"
            >
              <h3 className="font-medium text-blue-700">{s.title}</h3>
              <p className="text-sm text-gray-600 mt-1">{s.desc}</p>
            </Link>
          ))}
        </div>
      </section>
    </div>
  );
}
